# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: npmjs-sample-variables

resources:
  repositories:   
  - repository: templates
    type: git
    name: Operações/template-take-blip
    ref: refs/tags/v1.3.1

extends:
  template: template-pipeline.yml@templates    
  parameters:    
    packagename: blip-chat-extension
    type: javascript
    to: semantic-release
    npmCmds:
    - npm prune
    - npm run build
